spring:
  application:
    name: EventAPI

  datasource:
    url: jdbc:postgresql://localhost:5432/EventAPI
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
